### ISSUE TITLE
KeepAlive.init is not a function on client

### ISSUE THREAD

**Issue by stolinski** [trinisofttechnologies/keepalive#1]
Using 
```
KeepAlive.init({
    "website": "https://getatya.com", 
    "interval": 1000, 
});
```

Gives KeepAlive.init is not a function on client. Are there any more usage instructions?

**Comment by trinisofttechnologies** [comment]
Hi, Scott

Let me update the package.
And message you back.

**Comment by trinisofttechnologies** [comment]
Oh, keep alive is only for server side and not client side.

**Comment by stolinski** [comment]
Gotcha! I thought so, but the readme threw me off. Thanks for the amazingly fast response.
